services:
  dev:
    build:
      context: ./dev
      target: dev
    volumes:
      - ./:/workspace
      - ./app:/code # point to app code/container
      - root-history:/home/dev/history
      - vscode-server:/home/dev/.vscode-server
      - huggingface-cache:/home/dev/.cache/huggingface
      - google-vscode-extension-cache:/home/dev/.cache/google-vscode-extension
      - ~/.gemini:/home/dev/.gemini
      - ~/.claude:/home/dev/.claude
      - ~/.claude.json:/home/dev/.claude.json
      - /var/run/docker.sock:/var/run/docker.sock # expose docker socket
      - ~/.ssh:/home/dev/.ssh
      - ~/.config/gcloud:/home/dev/.config/gcloud
      - /home/dev/.docker
    stdin_open: true
    tty: true
    ports:
      - "8000:8000" # serving site
      - "5678:5678" # debugger
    env_file:
      - .env
    environment:
      GOOGLE_CLOUD_PROJECT: gemini-code-assist-466218 # used for gemini
      # Proxy defaults for dev-proxy.sh
      # PROXY_PORT: "3000"        # listen on dev:3000
      # TARGET_HOST: "ifx-app"    # target Next.js service name
      # TARGET_PORT: "3000"       # target port inside ifx-app
      # PROXY_BIND: "0.0.0.0"     # bind all interfaces so docker-proxy/VS Code can forward
      # PROXY_LOG_FILE: "/home/dev/proxy-3000.log" # log location inside dev
    # Start the proxy in background (from image), then keep the container alive for VS Code attach
    # command: ["sh", "-lc", "/usr/local/bin/dev-proxy.sh >/home/dev/proxy-3000.log 2>&1 & exec sleep infinity"]
    command: ["sleep", "infinity"]

  # app:
  #   build:
  #     context: ./app
  #     target: development
  #   volumes:
  #     - ./ifx-app:/app
  #     - /app/node_modules # This line is crucial. It creates an anonymous volume for node_modules, preventing the host's node_modules from overwriting the container's.
  #     - /app/.next # Same for .next, allowing Next.js to manage its build artifacts inside the container.
  #   # Entrypoint script in the image handles chown + fixuid + starting dev server

volumes:
  root-history:
    name: root-history
    external: true
  vscode-server:
    name: vscode-server
    external: true
  huggingface-cache:
    name: huggingface-cache
    external: true
  google-vscode-extension-cache:
    name: google-vscode-extension-cache
    external: true
